<?php
require_once "../auth/check.php"; require_once "../config/database.php";
$rootPath=".."; $activeNav="reports"; $pageTitle="Reports"; $pageSubtitle="Current fleet summary and operational snapshot";
$counts=["total"=>0,"online"=>0,"warning"=>0,"offline"=>0];
$r=mysqli_query($conn,"SELECT COUNT(*) total, SUM(status='online') online, SUM(status='warning') warning, SUM(status='offline') offline FROM servers"); if($r) $counts=array_map('intval',mysqli_fetch_assoc($r) ?: $counts);
$eventCount=0; $eventsTableReady=false; $tc=mysqli_query($conn,"SHOW TABLES LIKE 'alert_events'"); $eventsTableReady=$tc && mysqli_num_rows($tc)>0; if($eventsTableReady){$r=mysqli_query($conn,"SELECT COUNT(*) c FROM alert_events WHERE created_at >= (NOW() - INTERVAL 7 DAY)"); if($r) $eventCount=(int)(mysqli_fetch_assoc($r)["c"] ?? 0);}
$recent=[]; $r=mysqli_query($conn,"SELECT name,ip_address,os,status,updated_at FROM servers ORDER BY updated_at DESC, id DESC LIMIT 12"); if($r) while($row=mysqli_fetch_assoc($r)) $recent[]=$row;
require_once "../includes/head.php"; require_once "../includes/sidebar.php"; require_once "../includes/topbar.php";
?>
<div class="kpi-grid"><article class="kpi"><span class="kpi-label">Alert events · 7d</span><div class="kpi-value is-warn"><?= $eventCount ?></div></article><article class="kpi"><span class="kpi-label">Total nodes</span><div class="kpi-value"><?= $counts['total'] ?></div></article><article class="kpi"><span class="kpi-label">Online</span><div class="kpi-value is-ok"><?= $counts['online'] ?></div></article><article class="kpi"><span class="kpi-label">Warning</span><div class="kpi-value is-warn"><?= $counts['warning'] ?></div></article><article class="kpi"><span class="kpi-label">Offline</span><div class="kpi-value is-bad"><?= $counts['offline'] ?></div></article></div>
<section class="panel"><div class="panel-head"><div><h2>Operational snapshot</h2><p>Latest registered fleet records</p></div><button class="ghost-btn" type="button" onclick="window.print()"><i data-lucide="printer"></i> Print report</button></div><div class="table-scroll"><table class="data"><thead><tr><th>Server</th><th>Address</th><th>OS</th><th>Status</th><th>Last update</th></tr></thead><tbody><?php foreach($recent as $s): ?><tr><td><div class="server-title"><?=htmlspecialchars($s['name'])?></div></td><td class="mono"><?=htmlspecialchars($s['ip_address'])?></td><td><?=htmlspecialchars($s['os'] ?: '—')?></td><td><span class="pill pill-<?=htmlspecialchars($s['status'])?>"><?=htmlspecialchars($s['status'])?></span></td><td class="mono"><?=htmlspecialchars($s['updated_at'] ?: '—')?></td></tr><?php endforeach; ?><?php if(!$recent): ?><tr><td colspan="5" class="empty">Belum ada data fleet.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><h2>Recent alert events</h2><p>Status transitions captured by the monitoring API.</p></div><a class="ghost-btn" href="alerts.php">Open alerts</a></div><div class="table-scroll"><table class="data"><thead><tr><th>Time</th><th>Server</th><th>Transition</th><th>Event</th></tr></thead><tbody><?php $ev=$eventsTableReady ? mysqli_query($conn,"SELECT server_name,previous_status,status,event_type,created_at FROM alert_events ORDER BY id DESC LIMIT 10") : false; if($ev): while($e=mysqli_fetch_assoc($ev)): ?><tr><td class="mono"><?=htmlspecialchars($e["created_at"])?></td><td><?=htmlspecialchars($e["server_name"])?></td><td class="mono"><?=htmlspecialchars($e["previous_status"] ?: "new")?> → <?=htmlspecialchars($e["status"])?></td><td><span class="pill pill-<?= $e["event_type"] === "recovered" ? "online" : ($e["status"] === "offline" ? "offline" : "warning") ?>"><?=htmlspecialchars($e["event_type"])?></span></td></tr><?php endwhile; endif; ?></tbody></table></div></section>
<?php require_once "../includes/footer.php"; ?>
